### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by ghost** [matheusAlvarenga/next-boilerplate#1]
I think for a template you'd need to have the app be responsive to any device, so I'd just like to suggest you implement width break points and flex / grid.

**Comment by matheusAlvarenga** [comment]
I'll put this in my todo list with priority. Thanks for the advice! Do you have any suggestion?

**Comment by ghost** [comment]
Yeah you could use something like [this](https://grid.layoutit.com/) tool.
And setup screen break points using media queries, more info [here](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries).

Also sorry for the late response 😅
